# Generated by Django 4.1.6 on 2023-02-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_content_profile_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="../default_profile", upload_to="images/"),
        ),
    ]
