# Generated by Django 4.1.6 on 2023-02-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="movie_genre_filter",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4"), ("5", "5")],
                default="normal",
                max_length=1,
            ),
        ),
    ]
