# Generated by Django 4.1.6 on 2023-02-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ratings", "0002_rating_movie_genre_filter"),
    ]

    operations = [
        migrations.RemoveField(model_name="rating", name="movie_genre_filter",),
    ]
