# Generated by Django 4.1.6 on 2023-02-12 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_rename_user_movie_owner"),
        ("ratings", "0003_remove_rating_movie_genre_filter"),
    ]

    operations = [
        migrations.AddField(
            model_name="rating",
            name="movie",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="movies.movie",
            ),
            preserve_default=False,
        ),
    ]
