# Generated by Django 4.1.6 on 2023-02-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="movie_genre_filter",
            field=models.CharField(
                choices=[
                    ("action", "Action"),
                    ("horror", "Horror"),
                    ("drama", "Drama"),
                    ("western", "Western"),
                    ("thriller", "Thriller"),
                    ("comedy", "Comedy"),
                    ("scifi", "SciFi"),
                    ("romance", "Romance"),
                ],
                default="normal",
                max_length=32,
            ),
        ),
    ]
