# Generated by Django 4.1.6 on 2023-02-12 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_movie_genre_filter"),
    ]

    operations = [
        migrations.RemoveField(model_name="movie", name="owner",),
    ]
