# Generated by Django 4.1.6 on 2023-02-12 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_user"),
    ]

    operations = [
        migrations.RenameField(model_name="movie", old_name="user", new_name="owner",),
    ]
